# Generated by Django 4.2.7 on 2025-12-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='enable_password',
            field=models.CharField(blank=True, help_text='Deprecated: Use TACACS enable password from environment variables', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, help_text='Deprecated: Use TACACS credentials from environment variables', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='implementation_commands',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='post_check_commands',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='pre_check_commands',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='rollback_commands',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='validation_rules',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='implementation_results',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='post_check_results',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='pre_check_results',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='rollback_results',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
