# Generated by Django 4.2.7 on 2025-12-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_device_enable_password_alter_device_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='enable_password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='username',
        ),
    ]
