# Generated by Django 4.2.7 on 2025-12-10 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0003_remove_device_enable_password_remove_device_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug'), ('AUDIT', 'Audit')], default='INFO', max_length=10)),
                ('type', models.CharField(choices=[('SYSTEM', 'System'), ('AUTHENTICATION', 'Authentication'), ('DEVICE', 'Device'), ('WORKFLOW', 'Workflow'), ('CONFIGURATION', 'Configuration'), ('TACACS', 'TACACS')], default='SYSTEM', max_length=20)),
                ('message', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('old_values', models.TextField(blank=True)),
                ('new_values', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='automation__created_b916fb_idx'), models.Index(fields=['level'], name='automation__level_6c178d_idx'), models.Index(fields=['type'], name='automation__type_24125c_idx'), models.Index(fields=['object_type', 'object_id'], name='automation__object__2e9444_idx')],
            },
        ),
    ]
