# Generated by Django 4.2.7 on 2025-12-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0004_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('webhook_url', models.URLField(help_text='URL to send webhook notifications')),
                ('events', models.CharField(choices=[('execution_completed', 'Execution Completed'), ('execution_failed', 'Execution Failed'), ('execution_started', 'Execution Started'), ('all_events', 'All Events')], default='execution_completed', help_text='Events that trigger this webhook', max_length=20)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT')], default='POST', help_text='HTTP method to use for webhook', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is active')),
                ('secret_key', models.CharField(blank=True, help_text='Optional secret key for webhook verification', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
