# Generated by Django 4.2.7 on 2025-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_webhookconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='dynamic_params',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
