# Generated by Django 4.2.7 on 2025-12-12 05:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_workflowexecution_dynamic_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Variable name (e.g., 'interface_name', 'vlan_id')", max_length=100)),
                ('value', models.TextField(help_text='Variable value extracted from command output')),
                ('description', models.TextField(blank=True, help_text='Description of what this variable represents')),
                ('source_command', models.TextField(blank=True, help_text='The command that generated this variable')),
                ('source_stage', models.CharField(blank=True, choices=[('pre_check', 'Pre-Check'), ('implementation', 'Implementation'), ('post_check', 'Post-Check'), ('rollback', 'Rollback')], max_length=20)),
                ('extracted_using_regex', models.TextField(blank=True, help_text='The regex pattern used to extract this variable')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variable is still valid/active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='automation.workflowexecution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_execution', 'name'], name='automation__workflo_585e48_idx'), models.Index(fields=['workflow_execution', 'source_stage'], name='automation__workflo_3d9b52_idx'), models.Index(fields=['is_active'], name='automation__is_acti_1ebbec_idx')],
                'unique_together': {('workflow_execution', 'name')},
            },
        ),
    ]
