# Generated by Django 4.2.7 on 2025-12-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_add_workflow_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='required_dynamic_params',
            field=models.TextField(blank=True, default='[]', help_text='List of commands that require dynamic parameters'),
        ),
    ]
