# Generated by Django 4.2.7 on 2025-12-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_workflow_required_dynamic_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
