# Generated by Django 4.2.7 on 2025-12-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_workflow_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('sequence', 'Sequence Flow'), ('condition_true', 'True Condition'), ('condition_false', 'False Condition'), ('parallel', 'Parallel Flow')], default='sequence', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Edge label (e.g., 'Yes', 'No')", max_length=200)),
                ('condition_expression', models.TextField(blank=True, help_text='Edge condition expression')),
                ('position', models.JSONField(default=dict, help_text='Edge routing points for curved lines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['workflow', 'source_node', 'target_node'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='conditional_logic',
            field=models.TextField(blank=True, default='{}', help_text='Conditional execution logic for commands'),
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('command', 'Command'), ('condition', 'If/Else Condition'), ('start', 'Start'), ('end', 'End'), ('parallel_gateway', 'Parallel Gateway'), ('merge_gateway', 'Merge Gateway')], max_length=20)),
                ('name', models.CharField(help_text='Human-readable node name', max_length=200)),
                ('position_x', models.FloatField(default=0, help_text='X position in BPMN canvas')),
                ('position_y', models.FloatField(default=0, help_text='Y position in BPMN canvas')),
                ('width', models.FloatField(default=150, help_text='Node width')),
                ('height', models.FloatField(default=80, help_text='Node height')),
                ('command', models.TextField(blank=True, help_text='Command to execute')),
                ('regex_pattern', models.TextField(blank=True, help_text='Regex pattern for output validation')),
                ('operator', models.CharField(default='contains', help_text='Validation operator', max_length=20)),
                ('expected_output', models.TextField(blank=True, help_text='Expected output for testing')),
                ('stage', models.CharField(blank=True, help_text='Command stage (pre_check, implementation, etc.)', max_length=20)),
                ('is_dynamic', models.BooleanField(default=False, help_text='Whether command uses dynamic parameters')),
                ('store_in_variable', models.CharField(blank=True, help_text='Variable name to store output', max_length=100)),
                ('variable_description', models.TextField(blank=True, help_text='Description of stored variable')),
                ('condition_expression', models.TextField(blank=True, help_text='Condition expression (e.g., \'{variable_name} == "value"\')')),
                ('condition_variables', models.TextField(blank=True, default='[]', help_text='JSON array of variables used in condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.workflow')),
            ],
            options={
                'ordering': ['workflow', 'position_x', 'position_y'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_result', models.BooleanField(blank=True, help_text='Result of condition evaluation', null=True)),
                ('execution_order', models.IntegerField(help_text='Order in which this node was executed')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('edge_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.workflowedge')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.workflownode')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_paths', to='automation.workflowexecution')),
            ],
            options={
                'ordering': ['workflow_execution', 'execution_order'],
            },
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='automation.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='automation.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.workflow'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'node_type'], name='automation__workflo_a85490_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'position_x', 'position_y'], name='automation__workflo_f82cab_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionpath',
            index=models.Index(fields=['workflow_execution', 'execution_order'], name='automation__workflo_fb823c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionpath',
            index=models.Index(fields=['workflow_execution', 'node'], name='automation__workflo_b38c0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowexecutionpath',
            unique_together={('workflow_execution', 'execution_order')},
        ),
        migrations.AddIndex(
            model_name='workflowedge',
            index=models.Index(fields=['workflow', 'source_node'], name='automation__workflo_638fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowedge',
            index=models.Index(fields=['workflow', 'target_node'], name='automation__workflo_d7bb97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowedge',
            unique_together={('workflow', 'source_node', 'target_node')},
        ),
    ]
