# Generated by Django 4.2.7 on 2025-12-14 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0010_workflowedge_workflow_conditional_logic_workflownode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('playbook_content', models.TextField(help_text='YAML content of the Ansible playbook')),
                ('tags', models.TextField(blank=True, default='[]', help_text='JSON array of tags')),
                ('variables', models.TextField(blank=True, default='{}', help_text='JSON object of default variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('inventory_type', models.CharField(choices=[('static', 'Static Inventory'), ('dynamic', 'Dynamic Inventory')], default='static', max_length=20)),
                ('inventory_content', models.TextField(help_text='YAML/INI content of the inventory or script for dynamic')),
                ('group_variables', models.TextField(blank=True, default='{}', help_text='JSON object of group variables')),
                ('host_variables', models.TextField(blank=True, default='{}', help_text='JSON object of host variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('extra_vars', models.TextField(blank=True, default='{}', help_text='JSON object of extra variables')),
                ('tags', models.TextField(blank=True, default='[]', help_text='JSON array of tags to run')),
                ('skip_tags', models.TextField(blank=True, default='[]', help_text='JSON array of tags to skip')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.ansibleinventory')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.ansibleplaybook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleExecutionHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ok', 'OK'), ('changed', 'Changed'), ('failed', 'Failed'), ('unreachable', 'Unreachable'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_results', to='automation.ansibleexecution')),
            ],
            options={
                'ordering': ['execution', 'hostname', 'task_name'],
                'indexes': [models.Index(fields=['execution', 'hostname'], name='automation__executi_913f4e_idx'), models.Index(fields=['execution', 'status'], name='automation__executi_66c293_idx')],
            },
        ),
    ]
