# Generated by Django 4.2.7 on 2025-12-21 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0011_add_ansible_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='events',
            field=models.CharField(choices=[('execution_completed', 'Execution Completed'), ('execution_failed', 'Execution Failed'), ('execution_started', 'Execution Started'), ('ansible_execution_completed', 'Ansible Execution Completed'), ('ansible_execution_failed', 'Ansible Execution Failed'), ('ansible_execution_started', 'Ansible Execution Started'), ('all_events', 'All Events')], default='execution_completed', help_text='Events that trigger this webhook', max_length=100),
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of this device profile', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this device profile')),
                ('vendor', models.CharField(blank=True, help_text='Device vendor', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Device model', max_length=100)),
                ('os_version', models.CharField(blank=True, help_text='OS version', max_length=100)),
                ('device_type', models.CharField(blank=True, choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('load_balancer', 'Load Balancer'), ('server', 'Server'), ('other', 'Other')], help_text='Device type', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevicePlaybookMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this mapping', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this mapping does')),
                ('vendor', models.CharField(blank=True, help_text='Device vendor (exact match) - use device_profile instead', max_length=100)),
                ('model', models.CharField(blank=True, help_text='Device model (exact match) - use device_profile instead', max_length=100)),
                ('os_version', models.CharField(blank=True, help_text='OS version (exact match) - use device_profile instead', max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='Device type (exact match) - use device_profile instead', max_length=20)),
                ('workflow_type', models.CharField(help_text="Type of workflow (e.g., 'reboot', 'vlan_add', 'backup')", max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Priority for matching (higher = more specific)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('default_variables', models.TextField(blank=True, default='{}', help_text='JSON object of default variables for this mapping')),
                ('required_params', models.TextField(blank=True, default='[]', help_text='JSON array of required parameters for this workflow type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device_profile', models.ForeignKey(blank=True, help_text='Device profile containing metadata', null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.deviceprofile')),
                ('playbook', models.ForeignKey(help_text='Ansible playbook to execute', on_delete=django.db.models.deletion.CASCADE, to='automation.ansibleplaybook')),
            ],
            options={
                'ordering': ['-priority', 'workflow_type', 'device_profile__name'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceprofile',
            index=models.Index(fields=['vendor', 'model', 'os_version'], name='automation__vendor_5ca31a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceprofile',
            index=models.Index(fields=['device_type'], name='automation__device__44079d_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceplaybookmapping',
            index=models.Index(fields=['workflow_type', 'is_active'], name='automation__workflo_191191_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceplaybookmapping',
            index=models.Index(fields=['device_profile', 'workflow_type'], name='automation__device__de04cc_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceplaybookmapping',
            index=models.Index(fields=['vendor', 'model', 'os_version'], name='automation__vendor_fcd742_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceplaybookmapping',
            index=models.Index(fields=['priority', 'is_active'], name='automation__priorit_da51e2_idx'),
        ),
    ]
