# Generated by Django 4.2.7 on 2025-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_alter_webhookconfiguration_events_deviceprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceprofile',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='deviceplaybookmapping',
            options={'ordering': ['-priority', 'workflow_type']},
        ),
        migrations.RemoveIndex(
            model_name='deviceplaybookmapping',
            name='automation__device__de04cc_idx',
        ),
        migrations.RemoveField(
            model_name='deviceplaybookmapping',
            name='device_profile',
        ),
        migrations.AddField(
            model_name='deviceplaybookmapping',
            name='target_devices',
            field=models.ManyToManyField(blank=True, help_text='Specific devices this mapping applies to (leave empty to match by metadata)', to='automation.device'),
        ),
        migrations.AlterField(
            model_name='deviceplaybookmapping',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device type (exact match)', max_length=20),
        ),
        migrations.AlterField(
            model_name='deviceplaybookmapping',
            name='model',
            field=models.CharField(blank=True, help_text='Device model (exact match)', max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceplaybookmapping',
            name='os_version',
            field=models.CharField(blank=True, help_text='OS version (exact match)', max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceplaybookmapping',
            name='vendor',
            field=models.CharField(blank=True, help_text='Device vendor (exact match)', max_length=100),
        ),
        migrations.DeleteModel(
            name='DeviceProfile',
        ),
    ]
